Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = "http://127.0.0.1:3128/"
    config.proxy.https    = "http://127.0.0.1:3128/"
    config.proxy.no_proxy = "localhost,127.0.0.1,.example.com"
  end
end
